# Site settings
title: 点滴
email: recursion0210@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  空谈误国-实干兴邦
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://recursion0210.github.io/" # the base hostname & protocol for your site
twitter_username: recursion210
github_username:  Recursion0210

# Build settings
markdown: kramdown
